// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW6mCk09yjIy_ohRBR7dnzcYWfjtGx8S8',
    appId: '1:231669345397:web:a8a5eb5e69e2b6280cdc3c',
    messagingSenderId: '231669345397',
    projectId: 'bmi-app-cd9c7',
    authDomain: 'bmi-app-cd9c7.firebaseapp.com',
    storageBucket: 'bmi-app-cd9c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_-XSSyHY1woja9zuZX7Axn40J7o43cBA',
    appId: '1:231669345397:android:048cd55b0b8b59410cdc3c',
    messagingSenderId: '231669345397',
    projectId: 'bmi-app-cd9c7',
    storageBucket: 'bmi-app-cd9c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkrKyhQI8lANp80VhPDI924hGiHEDMoR0',
    appId: '1:231669345397:ios:56e6d7f5fb7f1f7f0cdc3c',
    messagingSenderId: '231669345397',
    projectId: 'bmi-app-cd9c7',
    storageBucket: 'bmi-app-cd9c7.appspot.com',
    iosBundleId: 'com.example.bmiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkrKyhQI8lANp80VhPDI924hGiHEDMoR0',
    appId: '1:231669345397:ios:4fb48fe881c67ff60cdc3c',
    messagingSenderId: '231669345397',
    projectId: 'bmi-app-cd9c7',
    storageBucket: 'bmi-app-cd9c7.appspot.com',
    iosBundleId: 'com.example.bmiApp.RunnerTests',
  );
}
